# Generated by Django 2.2.3 on 2020-03-31 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('propertyRating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(default='', max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystays.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Review', max_length=128)),
                ('impression', models.IntegerField(default=0)),
                ('locationRating', models.IntegerField(default=0)),
                ('cleanliness', models.IntegerField(default=0)),
                ('descripAccuracy', models.IntegerField(default=0)),
                ('costRating', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=255)),
                ('reviewedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystays.UserProfile')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystays.Stay')),
            ],
        ),
    ]
