# Generated by Django 2.2.3 on 2020-04-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='address',
        ),
        migrations.AddField(
            model_name='stay',
            name='keyword',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stay',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stay',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stay',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='stay_images/'),
        ),
    ]
