# Generated by Django 2.2.3 on 2020-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystays', '0002_auto_20200402_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
