# Generated by Django 2.2.3 on 2020-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystays', '0003_auto_20200401_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='stay_images/'),
        ),
    ]
